name: xmlable pypi publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Hatch
        run: pipx install hatch
      - name: test
        run: hatch run pytest
      - name: Build
        run: hatch build
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: hatch publish
